steps:
  - label: windows-test
    commands:
      # Yarn workspaces creates directory junctions inside node_modules, but these fail in docker.
      # E.g. inside the container, `mklink /J "C:\src\_" "C:\src\packages\_"` will fail with 
      # `Access is denied.`
      # https://github.com/moby/moby/issues/37024
      # As a workaround, we copy all files in the shared volume and run the commands in the new dir.
      - xcopy C:\workdir C:\workdir-copy /E /H /K /S /Q /I
      - cd C:\workdir-copy
      # Actual CI commands
      - yarn install --frozen-lockfile --non-interactive --network-timeout 500000
      - yarn webdriver-update-appveyor
      - node --version
      - yarn --version
      - yarn test
      - node tests\legacy-cli\run_e2e.js --appveyor "--glob=tests/{basic,commands,generate,build/styles}/**"
      # - bazel test ...
    plugins:
      - docker#v2.1.0:
          image: "filipesilva/node-bazel-windows:0.0.2"
    agents:
      windows: true
